services:
  postgis:
    image: postgis/postgis:16-3.4-alpine
    container_name: postgis_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: kirana
    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  postgis_data:
